#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio22
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_PRACTICA_CAPAS")]
	public partial class BD_PracticaLinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCLIENTES(CLIENTES instance);
    partial void UpdateCLIENTES(CLIENTES instance);
    partial void DeleteCLIENTES(CLIENTES instance);
    partial void InsertPRODUCTOS(PRODUCTOS instance);
    partial void UpdatePRODUCTOS(PRODUCTOS instance);
    partial void DeletePRODUCTOS(PRODUCTOS instance);
    partial void InsertDETALLE_FACTURA(DETALLE_FACTURA instance);
    partial void UpdateDETALLE_FACTURA(DETALLE_FACTURA instance);
    partial void DeleteDETALLE_FACTURA(DETALLE_FACTURA instance);
    partial void InsertENCABEZADO_FACTURA(ENCABEZADO_FACTURA instance);
    partial void UpdateENCABEZADO_FACTURA(ENCABEZADO_FACTURA instance);
    partial void DeleteENCABEZADO_FACTURA(ENCABEZADO_FACTURA instance);
    #endregion
		
		public BD_PracticaLinQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_PRACTICA_CAPASConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BD_PracticaLinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_PracticaLinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_PracticaLinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_PracticaLinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENTES> CLIENTES
		{
			get
			{
				return this.GetTable<CLIENTES>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCTOS> PRODUCTOS
		{
			get
			{
				return this.GetTable<PRODUCTOS>();
			}
		}
		
		public System.Data.Linq.Table<DETALLE_FACTURA> DETALLE_FACTURA
		{
			get
			{
				return this.GetTable<DETALLE_FACTURA>();
			}
		}
		
		public System.Data.Linq.Table<ENCABEZADO_FACTURA> ENCABEZADO_FACTURA
		{
			get
			{
				return this.GetTable<ENCABEZADO_FACTURA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTES")]
	public partial class CLIENTES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CLIENTE;
		
		private string _NOMBRE;
		
		private string _TELEFONO;
		
		private string _DIRECCION;
		
		private EntitySet<ENCABEZADO_FACTURA> _ENCABEZADO_FACTURA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CLIENTEChanging(int value);
    partial void OnID_CLIENTEChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    #endregion
		
		public CLIENTES()
		{
			this._ENCABEZADO_FACTURA = new EntitySet<ENCABEZADO_FACTURA>(new Action<ENCABEZADO_FACTURA>(this.attach_ENCABEZADO_FACTURA), new Action<ENCABEZADO_FACTURA>(this.detach_ENCABEZADO_FACTURA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLIENTE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CLIENTE
		{
			get
			{
				return this._ID_CLIENTE;
			}
			set
			{
				if ((this._ID_CLIENTE != value))
				{
					this.OnID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLIENTE = value;
					this.SendPropertyChanged("ID_CLIENTE");
					this.OnID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(11)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(80)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_ENCABEZADO_FACTURA", Storage="_ENCABEZADO_FACTURA", ThisKey="ID_CLIENTE", OtherKey="ID_CLIENTE")]
		public EntitySet<ENCABEZADO_FACTURA> ENCABEZADO_FACTURA
		{
			get
			{
				return this._ENCABEZADO_FACTURA;
			}
			set
			{
				this._ENCABEZADO_FACTURA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ENCABEZADO_FACTURA(ENCABEZADO_FACTURA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = this;
		}
		
		private void detach_ENCABEZADO_FACTURA(ENCABEZADO_FACTURA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTOS")]
	public partial class PRODUCTOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PRODUCTO;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIOCOMPRA;
		
		private decimal _PRECIOVENTA;
		
		private char _GRAVADO;
		
		private EntitySet<DETALLE_FACTURA> _DETALLE_FACTURA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PRODUCTOChanging(int value);
    partial void OnID_PRODUCTOChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnPRECIOCOMPRAChanging(decimal value);
    partial void OnPRECIOCOMPRAChanged();
    partial void OnPRECIOVENTAChanging(decimal value);
    partial void OnPRECIOVENTAChanged();
    partial void OnGRAVADOChanging(char value);
    partial void OnGRAVADOChanged();
    #endregion
		
		public PRODUCTOS()
		{
			this._DETALLE_FACTURA = new EntitySet<DETALLE_FACTURA>(new Action<DETALLE_FACTURA>(this.attach_DETALLE_FACTURA), new Action<DETALLE_FACTURA>(this.detach_DETALLE_FACTURA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this.OnID_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUCTO = value;
					this.SendPropertyChanged("ID_PRODUCTO");
					this.OnID_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIOCOMPRA", DbType="Decimal(10,2) NOT NULL")]
		public decimal PRECIOCOMPRA
		{
			get
			{
				return this._PRECIOCOMPRA;
			}
			set
			{
				if ((this._PRECIOCOMPRA != value))
				{
					this.OnPRECIOCOMPRAChanging(value);
					this.SendPropertyChanging();
					this._PRECIOCOMPRA = value;
					this.SendPropertyChanged("PRECIOCOMPRA");
					this.OnPRECIOCOMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIOVENTA", DbType="Decimal(10,2) NOT NULL")]
		public decimal PRECIOVENTA
		{
			get
			{
				return this._PRECIOVENTA;
			}
			set
			{
				if ((this._PRECIOVENTA != value))
				{
					this.OnPRECIOVENTAChanging(value);
					this.SendPropertyChanging();
					this._PRECIOVENTA = value;
					this.SendPropertyChanged("PRECIOVENTA");
					this.OnPRECIOVENTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRAVADO", DbType="Char(1) NOT NULL")]
		public char GRAVADO
		{
			get
			{
				return this._GRAVADO;
			}
			set
			{
				if ((this._GRAVADO != value))
				{
					this.OnGRAVADOChanging(value);
					this.SendPropertyChanging();
					this._GRAVADO = value;
					this.SendPropertyChanged("GRAVADO");
					this.OnGRAVADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTOS_DETALLE_FACTURA", Storage="_DETALLE_FACTURA", ThisKey="ID_PRODUCTO", OtherKey="ID_PRODUCTO")]
		public EntitySet<DETALLE_FACTURA> DETALLE_FACTURA
		{
			get
			{
				return this._DETALLE_FACTURA;
			}
			set
			{
				this._DETALLE_FACTURA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_FACTURA(DETALLE_FACTURA entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTOS = this;
		}
		
		private void detach_DETALLE_FACTURA(DETALLE_FACTURA entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETALLE_FACTURA")]
	public partial class DETALLE_FACTURA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_FACTURA;
		
		private int _ID_PRODUCTO;
		
		private System.Nullable<int> _CANTIDAD;
		
		private EntityRef<PRODUCTOS> _PRODUCTOS;
		
		private EntityRef<ENCABEZADO_FACTURA> _ENCABEZADO_FACTURA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FACTURAChanging(int value);
    partial void OnID_FACTURAChanged();
    partial void OnID_PRODUCTOChanging(int value);
    partial void OnID_PRODUCTOChanged();
    partial void OnCANTIDADChanging(System.Nullable<int> value);
    partial void OnCANTIDADChanged();
    #endregion
		
		public DETALLE_FACTURA()
		{
			this._PRODUCTOS = default(EntityRef<PRODUCTOS>);
			this._ENCABEZADO_FACTURA = default(EntityRef<ENCABEZADO_FACTURA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FACTURA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_FACTURA
		{
			get
			{
				return this._ID_FACTURA;
			}
			set
			{
				if ((this._ID_FACTURA != value))
				{
					if (this._ENCABEZADO_FACTURA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_FACTURAChanging(value);
					this.SendPropertyChanging();
					this._ID_FACTURA = value;
					this.SendPropertyChanged("ID_FACTURA");
					this.OnID_FACTURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					if (this._PRODUCTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUCTO = value;
					this.SendPropertyChanged("ID_PRODUCTO");
					this.OnID_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int")]
		public System.Nullable<int> CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this.OnCANTIDADChanging(value);
					this.SendPropertyChanging();
					this._CANTIDAD = value;
					this.SendPropertyChanged("CANTIDAD");
					this.OnCANTIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTOS_DETALLE_FACTURA", Storage="_PRODUCTOS", ThisKey="ID_PRODUCTO", OtherKey="ID_PRODUCTO", IsForeignKey=true)]
		public PRODUCTOS PRODUCTOS
		{
			get
			{
				return this._PRODUCTOS.Entity;
			}
			set
			{
				PRODUCTOS previousValue = this._PRODUCTOS.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCTOS.Entity = null;
						previousValue.DETALLE_FACTURA.Remove(this);
					}
					this._PRODUCTOS.Entity = value;
					if ((value != null))
					{
						value.DETALLE_FACTURA.Add(this);
						this._ID_PRODUCTO = value.ID_PRODUCTO;
					}
					else
					{
						this._ID_PRODUCTO = default(int);
					}
					this.SendPropertyChanged("PRODUCTOS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ENCABEZADO_FACTURA_DETALLE_FACTURA", Storage="_ENCABEZADO_FACTURA", ThisKey="ID_FACTURA", OtherKey="ID_FACTURA", IsForeignKey=true)]
		public ENCABEZADO_FACTURA ENCABEZADO_FACTURA
		{
			get
			{
				return this._ENCABEZADO_FACTURA.Entity;
			}
			set
			{
				ENCABEZADO_FACTURA previousValue = this._ENCABEZADO_FACTURA.Entity;
				if (((previousValue != value) 
							|| (this._ENCABEZADO_FACTURA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ENCABEZADO_FACTURA.Entity = null;
						previousValue.DETALLE_FACTURA.Remove(this);
					}
					this._ENCABEZADO_FACTURA.Entity = value;
					if ((value != null))
					{
						value.DETALLE_FACTURA.Add(this);
						this._ID_FACTURA = value.ID_FACTURA;
					}
					else
					{
						this._ID_FACTURA = default(int);
					}
					this.SendPropertyChanged("ENCABEZADO_FACTURA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ENCABEZADO_FACTURA")]
	public partial class ENCABEZADO_FACTURA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_FACTURA;
		
		private System.Nullable<System.DateTime> _FECHA;
		
		private int _ID_CLIENTE;
		
		private decimal _SUBTOTAL;
		
		private decimal _IMPUESTO;
		
		private decimal _MONTODESCUENTO;
		
		private EntitySet<DETALLE_FACTURA> _DETALLE_FACTURA;
		
		private EntityRef<CLIENTES> _CLIENTES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FACTURAChanging(int value);
    partial void OnID_FACTURAChanged();
    partial void OnFECHAChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHAChanged();
    partial void OnID_CLIENTEChanging(int value);
    partial void OnID_CLIENTEChanged();
    partial void OnSUBTOTALChanging(decimal value);
    partial void OnSUBTOTALChanged();
    partial void OnIMPUESTOChanging(decimal value);
    partial void OnIMPUESTOChanged();
    partial void OnMONTODESCUENTOChanging(decimal value);
    partial void OnMONTODESCUENTOChanged();
    #endregion
		
		public ENCABEZADO_FACTURA()
		{
			this._DETALLE_FACTURA = new EntitySet<DETALLE_FACTURA>(new Action<DETALLE_FACTURA>(this.attach_DETALLE_FACTURA), new Action<DETALLE_FACTURA>(this.detach_DETALLE_FACTURA));
			this._CLIENTES = default(EntityRef<CLIENTES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FACTURA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_FACTURA
		{
			get
			{
				return this._ID_FACTURA;
			}
			set
			{
				if ((this._ID_FACTURA != value))
				{
					this.OnID_FACTURAChanging(value);
					this.SendPropertyChanging();
					this._ID_FACTURA = value;
					this.SendPropertyChanged("ID_FACTURA");
					this.OnID_FACTURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLIENTE", DbType="Int NOT NULL")]
		public int ID_CLIENTE
		{
			get
			{
				return this._ID_CLIENTE;
			}
			set
			{
				if ((this._ID_CLIENTE != value))
				{
					if (this._CLIENTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLIENTE = value;
					this.SendPropertyChanged("ID_CLIENTE");
					this.OnID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTOTAL", DbType="Decimal(10,2) NOT NULL")]
		public decimal SUBTOTAL
		{
			get
			{
				return this._SUBTOTAL;
			}
			set
			{
				if ((this._SUBTOTAL != value))
				{
					this.OnSUBTOTALChanging(value);
					this.SendPropertyChanging();
					this._SUBTOTAL = value;
					this.SendPropertyChanged("SUBTOTAL");
					this.OnSUBTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMPUESTO", DbType="Decimal(10,2) NOT NULL")]
		public decimal IMPUESTO
		{
			get
			{
				return this._IMPUESTO;
			}
			set
			{
				if ((this._IMPUESTO != value))
				{
					this.OnIMPUESTOChanging(value);
					this.SendPropertyChanging();
					this._IMPUESTO = value;
					this.SendPropertyChanged("IMPUESTO");
					this.OnIMPUESTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTODESCUENTO", DbType="Decimal(10,2) NOT NULL")]
		public decimal MONTODESCUENTO
		{
			get
			{
				return this._MONTODESCUENTO;
			}
			set
			{
				if ((this._MONTODESCUENTO != value))
				{
					this.OnMONTODESCUENTOChanging(value);
					this.SendPropertyChanging();
					this._MONTODESCUENTO = value;
					this.SendPropertyChanged("MONTODESCUENTO");
					this.OnMONTODESCUENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ENCABEZADO_FACTURA_DETALLE_FACTURA", Storage="_DETALLE_FACTURA", ThisKey="ID_FACTURA", OtherKey="ID_FACTURA")]
		public EntitySet<DETALLE_FACTURA> DETALLE_FACTURA
		{
			get
			{
				return this._DETALLE_FACTURA;
			}
			set
			{
				this._DETALLE_FACTURA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_ENCABEZADO_FACTURA", Storage="_CLIENTES", ThisKey="ID_CLIENTE", OtherKey="ID_CLIENTE", IsForeignKey=true)]
		public CLIENTES CLIENTES
		{
			get
			{
				return this._CLIENTES.Entity;
			}
			set
			{
				CLIENTES previousValue = this._CLIENTES.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTES.Entity = null;
						previousValue.ENCABEZADO_FACTURA.Remove(this);
					}
					this._CLIENTES.Entity = value;
					if ((value != null))
					{
						value.ENCABEZADO_FACTURA.Add(this);
						this._ID_CLIENTE = value.ID_CLIENTE;
					}
					else
					{
						this._ID_CLIENTE = default(int);
					}
					this.SendPropertyChanged("CLIENTES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_FACTURA(DETALLE_FACTURA entity)
		{
			this.SendPropertyChanging();
			entity.ENCABEZADO_FACTURA = this;
		}
		
		private void detach_DETALLE_FACTURA(DETALLE_FACTURA entity)
		{
			this.SendPropertyChanging();
			entity.ENCABEZADO_FACTURA = null;
		}
	}
}
#pragma warning restore 1591
